### PR TITLE
Expose TCPSocket on 3310

### PR DESCRIPTION
**Pull request by kaleposhobios**
This is necessary for the way our other containers connect to this.

### CODE REVIEW

**Comment by kevinroche** [comment]
The [old Dockerfile](https://github.com/dinkel/docker-clamavd/blob/master/Dockerfile) also had `EXPOSE 3310`. Is that not needed anymore?

**Comment by kaleposhobios** [comment]
@kevinroche It worked for me without it (locally). It's possible (a) I did something weird or (b) it would work differently on Aptible. But I do think it would work and I'd like to try it?

**Comment by kevinroche** [comment]
Ok, not sure if you're familiar with it but we have a sandbox environment in Aptible which would be a great place for you to first deploy the image in Aptible and confirm it's working before we approve and push things to staging.
@JensAstrup or @jhyphen could help you out with how to use it if needed.

**Comment by kaleposhobios** [comment]
Thanks @kevinroche. Just to lay everything out:
[ ] Tested as a DockerHub container (from my fork)
[ ] Tested locally
[ ] Tested on Aptible sandbox
[ ] Tested on staging [running on Aptible]
[ ] Tested on production [running on Aptible]

What benefit would there be putting it on Aptible sandbox? Is there a way for me to have my local environment point to that as the server, or something? The only other benefit I can think of is watching the logs to make sure it starts up? 
Otherwise my plan was just, if we can get this merged, to build the image and deploy it to staging. Then staging should suddenly start working, right? Then ditto for production. And the web repo PR is really just for people's local testing anyway.

**Comment by kevinroche** [comment]
> Then staging should suddenly start working, right?
In general, when there are doubts about it working in Aptible because of differences between a local environment and Aptible (which usually there shouldn't be), then we use Sandbox to verify that so we don't negatively impact staging for everyone else. Staging is meant to be an environment for changes that have been tested and approved. I'm speaking in general terms here about how we normally do things, I only suggested the Sandbox step because of [this comment](https://github.com/Wellthy/docker-clamavd/pull/1#issuecomment-901247701). If you want to make the argument that we should go straight to staging for expediency of this particular change because this is an important security fix and you don't actually think there should be a difference in Aptible vs. your local setup then I'm fine with it. The worst that could happen is it breaks document uploads in staging which could potentially slow down other testing.

**Comment by kaleposhobios** [comment]
Hi @kevinroche,

No, ok, that makes sense. So:
[ X ] Tested as a DockerHub container (from my fork)
[ X ] Tested locally
[ ] Tested on Aptible sandbox
[ ] Tested on staging [running on Aptible]
[ ] Tested on production [running on Aptible]

Will you merge the PR so I can make the container and push to Aptible sandbox? Or do you want me to build from the PR branch?

**Review by kevinroche — APPROVED** [review]

**Comment by kevinroche** [comment]
Our normal process would be to build from the PR branch and deploy that to sandbox. That way, if you do need to make a change (like adding that `EXPORT` statement), we don't need another PR.

**Comment by kaleposhobios** [comment]
Thanks @kevinroche! Is `demo` (https://dashboard.aptible.com/accounts/3611/apps) on Aptible, the sandbox you mean?

**Comment by kevinroche** [comment]
No, it's the poorly named `wellthy-celery-test` env (which we should really get around to renaming).

`demo` is used for live demos to clients, investors, etc. and is meant to be stable so changes are deployed there when they are deployed to production.

**Comment by kaleposhobios** [comment]
@kevinroche Thanks! You were right, we do need the port. Added.

Testing steps I took after that:
1. `docker build -t wellthy/clamavd:kaleposhobios_fork .`
2. `docker push wellthy/clamavd:kaleposhobios_fork`
3. `aptible deploy --app clamavd --environment wellthy-celery-test --docker-image wellthy/clamavd:kaleposhobios_fork --private-registry-email=matt.horst@wellthy.com --private-registry-username=matthorst --private-registry-password=[redacted]`

Watch the logs:
`aptible logs --environment wellthy-celery-test --app clamavd`
>Local version: 0.102.4 Recommended version: 0.103.3
>2021-08-18T18:08:42.098Z [clamavd-cmd 51fd03dfc3ed - aptible]: container exceeded its memory allocation

That's not surprising, seeing that locally I had to increase my container size too.

I don't think I can see or modify the images it's using. What is sandbox using vs staging or prod? Can you help me up it?

**Comment by kevinroche** [comment]
If you login to the Aptible Deploy web console, you can view and update the container sizes there. You can also do it via the CLI: https://deploy-docs.aptible.com/docs/scaling

**Comment by kaleposhobios** [comment]
Thanks @kevinroche. I did look, I'm embarassed that I missed that. 

Ok now the logs show:
>2021-08-18T19:21:32.007Z [clamavd-cmd 89a8218b26c2]: Wed Aug 18 19:21:32 2021 -> Self checking every 3600 seconds.
So the clamavd image is working. I'm really happy about that!

Next problem -- I rammed my head against this for a few hours off and on, but I still can't solve it. Namely, the sandbox `web` container can't find sandbox `clamavd` container by name (which is the way it worked locally). Maybe there's some configuration happening in the CircleCI `docker-clamavd` build? Like maybe there's a `docker run ... --link clamavd:clamavd` happening for prod?

Or is it possible prod and sandbox virus scanning is down for multiple reasons? E.g. I *know* the outdated version is a problem. But is it possible the container links never worked and I need to fix that, too?

I'm asking for input in case you already know any of the answers, before I invest more time. Thanks!

**Comment by kevinroche** [comment]
Awesome. The containers get linked through internal endpoints within Aptible. I suspect that may be misconfigured [in the sandbox environment](https://dashboard.aptible.com/apps/18840/vhosts). I took a quick look and there are two endpoints defined for some reason. Basically there needs to be an internal endpoint defined for the `clamavd` container and then that needs to be set as the `CLAMD_TCP_ADDR` environment variable in the `web` app. We can try to walk through via screenshare if you want.

**Comment by kaleposhobios** [comment]
Hi @kevinroche,

Thanks! The two services were me, I was trying to expose the service myself to make sure it was really right. It gets weirder...I realized I could try connecting with netstat, and it works: From an ephemeral web worker I can `netstat app-18840.on-aptible.com 3310` and it seems to connect.

So I'd think everything is actually right. But when I actually try to run the scanner code, it can't connect. The innards of the scanner TCP connection code are getting a little bit deep for me. I do think the connection is available, because it doesn't IOError. It simply doesn't respond:

>clamd.ClamdNetworkSocket('app-18840.on-aptible.com', 3310).ping()
[no response, eventually times out I guess]

On my dev machine:
> clamd.ClamdNetworkSocket('clamavd', 3310).ping()
'PONG'

So maybe EVERYTHING about the version, failing to update DB, was all a red herring (good to solve but ultimately irrelevant). And maybe the only real problem is, for whatever reason, the TCP port is available but django-clamd isn't able to successfully talk to the clamd daemon. But only on aptible. Which...the reasons why that could be, are a bit beyond me. 

Any thoughts triggered by this?

**Comment by kevinroche** [comment]
Hmm, it's not clear to me if what you're seeing is specific to the sandbox environment or if it is reproducing an issue that exists in staging and prod. I think if this were the case (us not being able to connect to the container at all), then we would be seeing the error when trying to upload, as opposed to it silently passing due to an empty response as you earlier suggested.

**Comment by kaleposhobios** [comment]
Sandbox, staging, and prod all have the same behavior:
`get_scanner().ping()` returns an empty string (due to timeout I think) rather than either succeeding OR failing.

At first I thought the clam daemon was down because of being to old, it couldn't fetch new virus definitions. It *is* true that it can't be virus definitions, but now I'm thinking that's a red herring. I now think on no envs can django-clamd successfully connect over TCP 3310 and send commands to clamd. 

It *can* connect, hence no IOErrror and why `ping` and `netstat` work.

That's my current understanding. How about this theory -- locally the containers are linked so the ports are just open and the TCP connection works fine. But on Aptible, it's wrapped in TLS. Maybe it doesn't know how to navigate through that to successfully send and receive commands?

**Comment by kaleposhobios** [comment]
@kevinroche IT WORKED! I didn't realize that exposed new TCP (not TLS) port would have its own IP address that I'd have to hit.

Screen Shot 2021-08-18 at 7 12 54 PM

So therefore:
>clamd.ClamdNetworkSocket('elb-shared-us-east-1-doit-37267.aptible.in', 3310).ping()
WORKS!

>clamd.ClamdNetworkSocket('app-18840.on-aptible.com ', 3310).ping()
Doesn't work (exhibits same behavior as prod + staging).

So I have a line of sight to a fix. I'll need to figure out either how to make `expose 3310` expose it as a TCP port, NOT a TLS port, or I'll have to make it create a second endpoint and put that as the IP address in the web config.

I'm so happy!

**Comment by kaleposhobios** [comment]
@kevinroche Follow-up, do we do configuration as code for Aptium? Or is it just manual setup for the 3 environments? If so, we could just manually set up the right ports as TCP. 

I don't have access to prod Aptium. Nor for the docker-clamavd CircleCi project that I see we have. So I'm not sure how those work.

**Comment by kevinroche** [comment]
Great!

**Comment by kevinroche** [comment]
To answer the follow-up question, we don't currently have all of our Aptible configuration for things like endpoints in code so that would be manual. For things like that, our procedure is to explicitly document the steps (either the actions in the web console or CLI commands) that would be needed so we can ensure everyone agrees and approves of them prior to doing them.

**Comment by kaleposhobios** [comment]
Thanks @kevinroche! Here's what I propose. Can you please review and confirm if I can try this on `wellthy-celery-test`?

*Documented Aptible configuration steps*
a. Using web console, update `clamavd` to remove the current `Cmd service` endpoint (TLS)
b. Via command line, run this:
```
aptible endpoints:tcp:create --app clamavd --environment wellthy-celery-test cmd --default-domain --internal --ports 3310
```

*Order*
1. Try `wellthy-celery-test` first
2. Test on sandbox.wellthy.com

*Risks / questions*
1. File upload at all doesn't seem to work on sandbox. Shall we just validate the scanner function manually via shell, and move on?
2. I don't understand how the `CLAMD_TCP_ADDR` OS environment variable gets set. It does seem magically set on sandbox. But will it match up with the manually-created service name? I'm hoping by passing `--default-domain` that it will?

**Comment by sreynen** [comment]
If we're going to be trusting this docker image to handle all files in our platform, I think this repo should have a PR template with a checklist, just like our platform repo has.

**Comment by kaleposhobios** [comment]
@sreynen Sounds good to me, thanks for taking a look at this!

Previously we pulled from some Docker image we had no direct visibility into, based on a GitHub repo we didn't own. In the new world we'll own the Docker container and the GitHub repo. So at least we have a lot better visibility into it?

Incorporating what you suggested, maybe the final state of things could be like:
1. This docker image GitHub repo, with README specific to Wellthy's process and at minimum, a description of how to verify it still works for any PR introducing changes.
2. Defined path for how to set up Aptible environment for clamavd and web containers to work together (e.g. expose 3310 via TCP
3. CircleCI builder that pulls from this repo and pushes to the DockerHub image.
   a. @kevinroche I see that we do have a CircleCI project for clamav. But I don't know if it does what we want or not. Can you help us find out?

In the meantime, @sreynen + @kevinroche, it stinks that I'm out tomorrow and Monday. I think the next steps are for everyone to ok the plan above (specifically the Aptible steps) and try them out on sandbox, then staging, then prod. My intuition is that we could "fix" the prod issues with ONLY the Aptible changes. But, that doesn't fix the issue that the AV file definition is way out of date. Having staging + prod use this Docker container, not `dinkel`'s, will fix that.

Thanks and sorry for the novel!

**Comment by kevinroche** [comment]
@kaleposhobios apologies for not responding to your earlier questions quicker, I forgot you were out tomorrow and Mon.

From your most recent comment:
#1 and #2 sound good. As for #3, we don't yet have a CircleCI project for this repo, I think you may been misled by the fact they automatically list all repos, but note the "Set Up Project" button:
image

As for your earlier comment on the approach for the change:
I would want to understand if between steps a and b, our file uploading would become unavailable. We can confirm that when doing this in staging. If it is, then we'll want to discuss timing for the change in prod.
`CLAMD_TCP_ADDR` is set as a config variable in Aptible. We would update the value using the [aptible config:set command](https://deploy-docs.aptible.com/docs/cli-config-set) so that would be another deployment step.

**Comment by kaleposhobios** [comment]
Hi @kevinroche,

Thanks for this. I don't have the right permissions in CircleCI, I just get a lock icon:
Screen Shot 2021-08-19 at 7 27 13 PM

Your 3 steps sound great. I doubt we'll have downtime, but like you said we can confirm. Or alternatively, we can use config variable to completely disable AV scanning, which will make it just pass through and allow uploads. Then once we manually test the new TCP port availability and confirm it can connect (via prod/staging shell) we can turn back on AV scanning.

I have no access to production, so I'll need a pairing buddy to help with real deploy. 

Unless one of you works on this, when I get back I can test out the steps on sandbox. Are you fine with me testing those same steps on staging, too, if it works? I believe we'll need to test end-to-end on staging only since sandbox file uploads don't actually work (which I assume is a known issue with sandbox?).

**Comment by kaleposhobios** [comment]
@kevinroche Made a bunch of updates. Can you take a look now? The one thing I didn't do was remove the old endpoint -- it doesn't actually let me delete it because it's the default one. Maybe I could modify the old one to be non-default then modify the new one to be default. But...does it matter?

I tested on sandbox and upload was successfully blocked!

**Comment by kevinroche** [comment]
Looks good. Do we have follow-up stories to have this deployed via CircleCI in the future and to add a PR template for this repo as Scott suggested? I don't want to hold up this fix but also think this is worth doing as a follow-up.

As for cleaning up the old endpoints:
> does it matter?

It doesn't for the purpose of fixing the issue, but I'd like us to be in the habit of keeping our environments clean and not leave things around that aren't needed or they'll build up over time and create confusion for future engineers.

**Comment by kaleposhobios** [comment]
Thanks Kevin. I'll create those stories and update the README to include cleanup of the old endpoint.

Just to be safe, can you confirm I'm ok to test this on staging right now with the above procedure?

**Review by kevinroche — APPROVED** [review]

**Comment by kevinroche** [comment]
Approved to continue to staging. For posterity, please comment here with links to the new stories once created.

**Pull request merged**
